In [2]:
import torch
import torch.nn as nn


Transform Using A Matrix


In [12]:
in_features = torch.tensor([1,2,3,4],dtype=torch.float32)
print(in_features.size())

weight_matrix = torch.tensor([[1,2,3,4],[2,3,4,5],[3,4,5,6]],dtype=torch.float32)
print(weight_matrix.size())

weight_matrix.matmul(in_features)

#In general, the weight matrix defines a linear function that maps a 1-dimensional tensor with four elements to a 1-dimensional tensor that has three elements. We can think of this function as a mapping from 4-dimensional Euclidean space to 3-dimensional Euclidean space.

torch.Size([4])
torch.Size([3, 4])


tensor([30., 40., 50.])

In [13]:
fc = nn.Linear(in_features = 4, out_features = 3) #pytorch lin layer doing same operation as above

Transform Using A PyTorch Linear Layer (we'll do same using pytorch linear layer)

In [13]:

fc = nn.Linear(in_features=4, out_features=3, bias=False)

#Here, we have it. We've defined a linear layer that accepts 4 in features and transforms these into 3 out features, so we go from 4-dimensional space to 3-dimensional space

#weight matrix is lives inside the PyTorch LinearLayer class and is created by PyTorch. The PyTorch LinearLayer class uses the numbers 4 and 3 that are passed to the constructor to create a 3 x 4 weight matrix

In [15]:
#Let's see how we can call our layer now by passing the in_features tensor.

#We can call the object instance like this because PyTorch neural network modules are callable Python objects.

fc(in_features)

#Let's explicitly set the weight matrix of the linear layer to be the same as the one we used in our other example.

fc.weight = nn.Parameter(weight_matrix)  


#now we got same ouput [30,40,50] like previous 

In [27]:
fc(in_features)

#This time we are much closer to the 30, 40, and 50 values. However, we're exact. Why is this? We'll, this is not exact because the linear layer is adding a bias tensor to the output. 

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)

In [30]:
fc = nn.Linear(in_features=4, out_features=3, bias=False) 
fc.weight = nn.Parameter(weight_matrix)

In [31]:
fc(in_features)

#now we get same values as bias is false 

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)

Callable Layers And Neural Networks


In [16]:
fc(in_features)

#What makes this possible is that PyTorch module classes implement another special Python function called __call__(). If a class implements the __call__() method, the special call method will be invoked anytime the object instance is called.

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)

Instead of calling the forward() method directly, we call the object instance. After the object instance is called, the __call__() method is invoked under the hood, and the __call__() in turn invokes the forward() method. This applies to all PyTorch neural network modules, namely, networks and layers.

In [17]:
fc = nn.Linear(in_features = 4, out_features = 3)

t = torch.tensor([1,2,3], dtype = torch.float32)

output = fc(t)

print(output)

RuntimeError: size mismatch, m1: [1 x 3], m2: [4 x 3] at ..\aten\src\TH/generic/THTensorMath.cpp:41