In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torchvision
import torchvision.transforms as transforms

torch.set_printoptions(linewidth = 120)

In [7]:
train_set = torchvision.datasets.FashionMNIST(
    root='./data'  
    ,train=True    
    ,download=True 
    ,transform=transforms.Compose([
        transforms.ToTensor()
    ])
)

In [8]:
class Network(nn.Module):
        
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)

        self.fc1 = nn.Linear(in_features=12 * 4 * 4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)


    def forward(self, t):
     
        t = F.relu(self.conv1(t) )
        t = F.max_pool2d(t, kernel_size = 2, stride =2)

        t = F.relu(self.conv2(t))
        t = F.max_pool2d(t, kernel_size = 2, stride =2)

        t = F.relu(self.fc1(t.reshape(-1, 12*4*4)))
        t = F.relu(self.fc2(t))
        t = self.out(t)
        return t

In [10]:
torch.set_grad_enabled(False) #stops the gradient calculations as it keeps the tracks of compution using dynamics computation graph

In [11]:
network = Network()

In [12]:
sample = next(iter(train_set))

In [13]:
image, label = sample
image.shape

torch.Size([1, 28, 28])

In [14]:
#but nn deals with 4d tensors 

image.unsqueeze(0).shape #gives teh batch with size 1

torch.Size([1, 1, 28, 28])

In [15]:
pred = network(image.unsqueeze(0)) # image shape needs to be (size x channels x H x W)

In [16]:
pred.shape

torch.Size([1, 10])

In [17]:
pred


tensor([[ 0.1110,  0.1273,  0.0883,  0.0080, -0.0715, -0.1052,  0.1299, -0.0625, -0.0313,  0.1627]])

In [18]:
label #label for the first image in the set is 9

9

In [22]:
pred.argmax(dim = 1)

tensor([9])

In [62]:
F.softmax(pred, dim=1)

tensor([[0.0960, 0.0978, 0.0829, 0.0963, 0.1003, 0.0918, 0.1076, 0.1076, 0.1083, 0.1114]])

In [61]:
F.softmax(pred, dim=1).sum()

tensor(1.0000)

the weights here are random so each time we create a new instance of class the weights would be varying
#
so predictions from 2 different networks would not be same 
#
so if u create net2 and do the same the prediction would be different 